[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
tracing = "0.1.40"
crossbeam-channel = "0.5.13"
smol = "2.0.2"
bytes = "1.10"
log = "0.4"
thiserror = "2.0.12"
